### ISSUE TITLE
auto Start Program

### ISSUE THREAD

**Issue by Harry-McGill2021** [elewin/pi-weather-station#12]
is their a way to auto start the program when the pi boots up?

**Comment by mlcampbe** [comment]
Take a look at the reddit thread at https://www.reddit.com/r/raspberry_pi/comments/il03rk/i_made_weather_station_app_and_designed_it_for_a/ and you will get some pointers. The general directions are:

Step 1. Comment out the line in /home/pi/pi-weather-station/server/index.js that says:

// await open(http://localhost:${PORT});
Save that file.

Then create a file, /home/pi/.config/lxsession/LXDE-pi/autostart

touch /home/pi/.config/lxsession/LXDE-pi/autostart
Edit with your favorite editor and put in code similar to the following:

@xset s noblank
@xset s off
@xset -dpms
@bash /home/pi/weather.sh

Then create the referenced /home/pi/weather.sh and add the following:

#!/bin/bash
cd ~/pi-weather-station/
/usr/local/bin/npm start ~/pi-weather-station/server/index.js &
chromium-browser --noerrdialogs --disable-inforbars --incognito --kiosk http://localhost:8000/&

Then chmod +x weather.sh to make it executable. Reboot, and your display will pop up Chromium in kiosk mode, incognito, with no errors. I did get the upgrade dialog though so I need to find a way to disable that.

I found that when the pi boots chromium starts up but initially gets a page not found error. That goes away about 10 sec later automatically though once the npm server starts up.
