### ISSUE TITLE
NOM looking for package.json   

### ISSUE THREAD

**Issue by Rot10Crotch** [elewin/pi-weather-station#15]
Thank you for taking the time & effort to make this. Unfortunately, I am unable  to get it running. First off I have node V14.17 on an up to date RPi 3B. when I issue the command npm start, I Get the following response:
npm ERR! syscall open
npm ERR! path /home/pi/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-05-26T16_13_08_108Z-debug.log
[2021-05-26T16_13_08_108Z-debug.log](https://github.com/elewin/pi-weather-station/files/6548407/2021-05-26T16_13_08_108Z-debug.log)

It seems it is looking for package.json. I am attaching the log file. 

BTW While installing I had to a command like npm audit-fix - I don't know if it is relevant but thought I would mention it.

Edit: Title should read "**NPM looking for package.json**"

**Comment by ragd011** [comment]
I just installed this myself on an RPI with touchscreen.  When you clone from Git, you should have a directory called pi-weather-station.  You want to cd into that and then run npm start.  That's where the package.json is to get it started I believe.

**Comment by elewin** [comment]
@ragd011 Is exactly right, after cloning the project you have to go into the directory it creates before running `npm install`
