### ISSUE TITLE
How to add barometric pressure trend chart?

### ISSUE THREAD

**Issue by snakyjake1** [elewin/pi-weather-station#17]
How could I write something to add barometric trend chart?

Thank you.

**Comment by elewin** [comment]
You would first need to see if what you want is provided by the weather API that is being used, and then add what you want to the chart components in the `weatherCharts` directory. The charts are using [react-chartjs-2](https://www.npmjs.com/package/react-chartjs-2) which has documentation on how to create custom charts.
