### ISSUE TITLE
Hi how to remove settings button from web page?

### ISSUE THREAD

**Issue by v222008** [elewin/pi-weather-station#18]
![replace](https://user-images.githubusercontent.com/4614427/123505709-50c61100-d669-11eb-9cb3-6d67ad1f9928.jpg)

thx.

**Comment by elewin** [comment]
Comment out or remove this line: 
https://github.com/elewin/pi-weather-station/blob/5882f416154f760180f586424674b9cc2caf8f37/client/src/components/ControlButtons/index.js#L55
And then re-run webpack: `npm run prod`. 
Note however that without the ability change settings, you won't be able to update your API keys through the UI (though you can do so manually by updating the `settings.json` file that is generated)
