### ISSUE TITLE
Node.js install but no npm install

### ISSUE THREAD

**Issue by Owusses** [elewin/pi-weather-station#21]
I did follow all the steps but after node.js installed I can't install npm.
There was an error about locale not right.

**Comment by Owusses** [comment]
![20211125_174101.jpg](https://user-images.githubusercontent.com/87152303/143505380-5481e050-4338-4d1f-a16e-2207ad81fe88.jpg)
Can you help me fix this bash whenever I enter nmp install?

**Comment by elewin** [comment]
NPM comes with the node install, make sure node is installed correctly
