### ISSUE TITLE
Unable to retrieve map data

### ISSUE THREAD

**Issue by k5map** [elewin/pi-weather-station#30]
I've had my pi-weather-station up and running for almost a month but earlier today, my RPi stopped being able to download the map from Mapbox.  I waited 8 hours to see if the problem would resolve itself but it did not.  I then checked the Mapbox website and the API key was still valid and showed no problems.  To confirm the API key was not the issue, I had Mapbox issue a new key.  After entering this new key into the RPi, it is still unable to download the map.  Anyone have any ideas how to fix this?

**Comment by lerilar** [comment]
Same here, this however shows data:
https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/10.5977,59.7777,9.3,0/800x480?access_token=<yourkey>

I have also noticed two orange/yellow shapes that seems to be stuck on the weather map. You can see them on https://www.rainviewer.com/weather-radar-map-live.html using the same coordinates. (Svelvik, south of Oslo, Norway)
![image](https://user-images.githubusercontent.com/73758647/175047003-4b4a42e3-4ec9-487c-b6e0-6d2f779d8964.png)

**Comment by k5map** [comment]
My issue was resolved by making the change outlined in Issue #32
