### ISSUE TITLE
'Cannot retrieve map data -- did you enter an API key'

### ISSUE THREAD

**Issue by tmatthews5511** [elewin/pi-weather-station#33]
I get this error:

'Cannot retrieve map data -- did you enter an API key'

I put in the mapbox api key and I have waited about one hour, so far no result (this is the first time starting).

**Comment by k5map** [comment]
@tmatthews5511 

I had a similar problem and resolved it by manually entering the lat/lon of my location.

**Comment by tmatthews5511** [comment]
Bingo! That got it. Thank you kindly for the quick solution, you made my day! (I'm a total weather nerd).
