### ISSUE TITLE
How to change width of the right column?

### ISSUE THREAD

**Issue by jnemonic** [elewin/pi-weather-station#34]
Just looking for some customization options on the UI...Would also be nice to add a column to news api..

**Comment by elewin** [comment]
It’s all CSS

https://github.com/elewin/pi-weather-station/blob/05ed3f03a007451e4e8c1442405d0d9921442735/client/src/components/App/styles.css#L7

You can also open your browser’s dev tools and make adjustments to the CSS to see what potential changes might look like too, to play around with it
