### ISSUE TITLE
Error 403 for 7-day weather forecast

### ISSUE THREAD

**Issue by mf1x** [elewin/pi-weather-station#38]
Hi,

For a couple of weeks now I have been getting the following error message where the 7-day forecast should be:

"Cannot get 7 day weather forecast
Request failed with status code 403"

Has the weather provider changed something?

Edit: Same with the Docker version.

Regards
Max

**Comment by k5map** [comment]
I'm experiencing the same problem but don't know when it started.

**Comment by ZeroCool-Dade** [comment]
I have the same issue, wondering if its related to the tomorrow.io free account only gets a 5 day forecast?

**Comment by mf1x** [comment]
Could be. Have they changed that recently?

**Comment by k5map** [comment]
I just logged into my Tomorrow.io account and it shows no calls for my account.  Anyone know if the current weather is coming from Tomorrow or Mapbox?

**Comment by klamer** [comment]
I'm so glad I'm not the only one.  Been looking for this issue for at least a week or two.  I'm making the API call into tomorrow.io but just getting the 24 hour.
![tomorrow](https://github.com/elewin/pi-weather-station/assets/2219214/a7f64b8f-dd70-4708-a8b1-a61e883f2462)

**Comment by mf1x** [comment]
Let's hope someone can help :D

**Comment by klamer** [comment]
I messaged him on reddit, I'm hoping it's an easy fix...<shrug> I'm no coder.

**Comment by k5map** [comment]
@jbeckley11 ... can't thank you enough for figuring this out issue and coming up with the fix.

**Comment by jbeckley11** [comment]
@k5map To rebuild the project, navigate into the client folder and do `npm run prod`
Then go back to the app directory and do `npm start`

**Comment by k5map** [comment]
@jbeckley11 ... thanks for the commands.  When I run "npm run prod", I get this error:

pi@pi-Weather:~/pi-weather-station/client $ npm run prod

> pi-weather-station-client@1.0.0 prod
> webpack -p --env.BUILD_PRODUCTION=1

sh: 1: webpack: not found
npm ERR! code 127
npm ERR! path /home/pi/pi-weather-station/client
npm ERR! command failed
npm ERR! command sh -c webpack -p --env.BUILD_PRODUCTION=1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2023-06-04T11_48_42_756Z-debug.log

Any ideas what could be wrong?

**Comment by ZeroCool-Dade** [comment]
@k5map   not sure if its the correct way to do it but this is how I got around the webpack error.. :
from the client folder run 
sudo npm install
sudo npm run prod

**Comment by k5map** [comment]
@ZeroCool-Dade ... that did it, Much Thanks!

**Comment by elewin** [comment]
#39 
7 day forecast changed to 5 day forecast to meet new API requirements

**Comment by k5map** [comment]
@elewin... this is not a big deal but did you also update file client/src/components/weatherCharts/DailyCharts/index.js line 30 from 7 Day to 5 Day?

**Comment by elewin** [comment]
> @elewin... this is not a big deal but did you also update file client/src/components/weatherCharts/DailyCharts/index.js line 30 from 7 Day to 5 Day?

Yep!

https://github.com/elewin/pi-weather-station/pull/39/commits/da05477d54831834e1fc600f6ed6af68c0c4038a

**Comment by mf1x** [comment]
@elewin Are you able to merge the fix with Sean Riggs's Docker fork?

Edit: Never mind, I updated the file in the container.

**Comment by klamer** [comment]
Thanks all for their help in resolving this and @elewin for updating the code.

**Comment by mf1x** [comment]
Yep. Thanks a lot guys :)

**Comment by duarch** [comment]
What about docker image?
![Captura de Tela 2023-06-19 às 21 46 44](https://github.com/elewin/pi-weather-station/assets/42032253/6386e3cd-acde-45cf-9815-efd140b21a09)

**Comment by mf1x** [comment]
Not sure. I haven't gotten any response regarding this topic. I guess you need to change it yourself for now.

Install nano inside the container and change it (it's Alpine Linux btw).

**Comment by seancasey0702** [comment]
> Had this issue so I looked into it. This is because the free tier only lets you show 5 days into the future. To fix this, go to client\src\AppContext.js on line 377: `new Date().getTime() + 6 * 60 * 60 * 24 * 1000` Change the 6 to a 5, rebuild the project and it should work.

I tried this and I'm still getting an error code 403 on the 5-day forecast. I restarted the server, tried rebuilding it, everything. Any ideas?

**Comment by IamPatticus** [comment]
I can't seem to get the docker image to reflect the changes to the AppContext.js and Index.js ....not a big deal but would like to see the error go away :)
