### ISSUE TITLE
7 Day forecast no longer working

### ISSUE THREAD

**Issue by Map63Vette** [elewin/pi-weather-station#40]
I've had my weather station going on a spare Pi I have for several months at this point, but I was constantly having undervoltage issues with my power supply.  Finally got around to getting a new power supply for it, but after rebooting I'm no longer getting the 7 day forecast.  It's coming back with a 403 error, but the hourly forecast is working fine, so not quite sure I understand what might be wrong.  Would have thought if the API was bad it would take out all the weather info, but it's just the 7 day forecast.  Not sure if something changed on the Tomorrow.io side, but seems odd it would have happened exactly when I changed power supplies.  Have left it running for a day or two now thinking maybe it would just come back eventually, but still seeing the same error.

**Comment by elewin** [comment]
They recently changed their API to only allow 5 day forecasts on their free tier, and as a result I made an update to the app that only retrieves a 5 day forecast instead of 7. Download and install the latest version of the repo to get the changes.

Also see this: #38
