### ISSUE TITLE
NOT AN ISSUE...Just a question about map colors

### ISSUE THREAD

**Issue by crwdplezer** [elewin/pi-weather-station#43]
Wonder if possible to create a custom map in MapBox and then have it associate with the API Kep so that it displays something other than just light or dark mode on the display

**Comment by elewin** [comment]
It’s been a while since I’ve looked at it but mapbox doe support different appearance styles, if you poke around their docs they have something about how to switch it around

**Comment by crwdplezer** [comment]
I think I just figured it out. Thanks for the reply!On Aug 16, 2023 3:32 PM, Eric ***@***.***> wrote:
It’s been a while since I’ve looked at it but mapbox doe support different appearance styles, if you poke around their docs they have something about how to switch it around

**Comment by k5map** [comment]
@crwdplezer ... could you share with everyone the details?
