### ISSUE TITLE
Stablility issues

### ISSUE THREAD

**Issue by savilan77** [elewin/pi-weather-station#9]
First, thank you for the  great code. Mine works well in the beginning, but after some hours of use the webserver crashes and stops responding.  I have the same issue with two different raspberry boards. Any tips how to solve the issue?

**Comment by STFUandFish** [comment]
What hardware is this aimed at? I ran hamweather for years on a 3 A+ with zero problems, this thing drives it into the ground.

I tried a 3 B+, same problem.

**Comment by STFUandFish** [comment]
Update: Runs on 3 B+. Had to weak down the GPU RAM. I don't know why, but at higher RAM settings it forced pretty much everything to swap.

**Comment by savilan77** [comment]
I am running on Raspberry 4. I guess I have solved my case. I run Pi Weather Station with nodemon and it has been stable last week or so.
